trigger:
  tags:
    include:
    - 'v*'
    
pool:
  vmImage: ubuntu-latest

jobs:
  - job: ReleaseArtifactAndDocs
    steps:
      - checkout: self
        fetchDepth: all
        fetchTags: true

      - template: Version.yaml
        parameters:
          tagName: $(Build.SourceBranchName)  

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"
          addToPath: true
        displayName: "Use Python 3.12"

      - template: Test.yaml
      - template: Build.yaml
      - template: Publish.yaml
